project: 
  type: website
  output-dir: docs
  
website: 
  title: "STAT 515 - Final Project : Template"
  navbar: 
    left: 
      - index.qmd
      - codes.qmd
      - ref.qmd
      
format: 
  html: 
    theme: cosmo